def test_fail_intentionally():
    assert False